const networks = {
  polygon: {
    chainId: `0x${Number(137).toString(16)}`,
    chainName: "Polygon Mainnet",
    nativeCurrency: {
      name: "MATIC",
      symbol: "MATIC",
      decimals: 18,
    },
    rpcUrls: ["https://polygon-rpc.com/"],
    blockExplorerUrls: ["https://polygonscan.com/"],
  },
  bsc: {
    chainId: `0x${Number(56).toString(16)}`,
    chainName: "Binance Smart Chain Mainnet",
    nativeCurrency: {
      name: "Binance Chain Native Token",
      symbol: "BNB",
      decimals: 18,
    },
    rpcUrls: [
      "https://bsc-dataseed1.binance.org",
      "https://bsc-dataseed2.binance.org",
      "https://bsc-dataseed3.binance.org",
      "https://bsc-dataseed4.binance.org",
      "https://bsc-dataseed1.defibit.io",
      "https://bsc-dataseed2.defibit.io",
      "https://bsc-dataseed3.defibit.io",
      "https://bsc-dataseed4.defibit.io",
      "https://bsc-dataseed1.ninicoin.io",
      "https://bsc-dataseed2.ninicoin.io",
      "https://bsc-dataseed3.ninicoin.io",
      "https://bsc-dataseed4.ninicoin.io",
      "wss://bsc-ws-node.nariox.org",
    ],
    blockExplorerUrls: ["https://bscscan.com"],
  },
};

const connectToNetworks = [
  {
    name: "Goerli",
    title: "Ethereum Testnet Goerli",
    chain: "ETH",
    rpc: [
      "https://goerli.infura.io/v3/${INFURA_API_KEY}",
      "wss://goerli.infura.io/v3/${INFURA_API_KEY}",
      "https://rpc.goerli.mudit.blog/",
    ],
    faucets: [
      "http://fauceth.komputing.org?chain=5&address=${ADDRESS}",
      "https://goerli-faucet.slock.it?address=${ADDRESS}",
      "https://faucet.goerli.mudit.blog",
    ],
    nativeCurrency: {
      name: "Goerli Ether",
      symbol: "ETH",
      decimals: 18,
    },
    infoURL: "https://goerli.net/#about",
    shortName: "gor",
    chainId: 5,
    networkId: 5,
    ens: {
      registry: "0x112234455c3a32fd11230c42e7bccd4a84e02010",
    },
    explorers: [
      {
        name: "etherscan-goerli",
        url: "https://goerli.etherscan.io",
        standard: "EIP3091",
      },
    ],
    hide: true,
  },
  {
    chainId: 137,
    networkId: 137,
    name: "Polygon Mainnet",
    nativeCurrency: {
      name: "MATIC",
      symbol: "MATIC",
      decimals: 18,
    },
    rpcUrls: ["https://polygon-rpc.com/"],
    blockExplorerUrls: ["https://polygonscan.com/"],
    hide: true,
  },
  {
    hide: true,
    chainId: 56,
    networkId: 56,
    name: "Binance Smart Chain Mainnet",
    nativeCurrency: {
      name: "Binance Chain Native Token",
      symbol: "BNB",
      decimals: 18,
    },
    rpcUrls: [
      "https://bsc-dataseed1.binance.org",
      "https://bsc-dataseed2.binance.org",
      "https://bsc-dataseed3.binance.org",
      "https://bsc-dataseed4.binance.org",
      "https://bsc-dataseed1.defibit.io",
      "https://bsc-dataseed2.defibit.io",
      "https://bsc-dataseed3.defibit.io",
      "https://bsc-dataseed4.defibit.io",
      "https://bsc-dataseed1.ninicoin.io",
      "https://bsc-dataseed2.ninicoin.io",
      "https://bsc-dataseed3.ninicoin.io",
      "https://bsc-dataseed4.ninicoin.io",
      "wss://bsc-ws-node.nariox.org",
    ],
    blockExplorerUrls: ["https://bscscan.com"],
  },
  {
    name: "Ethereum Classic Testnet Kotti",
    chain: "ETC",
    rpc: ["https://www.ethercluster.com/kotti"],
    faucets: [],
    nativeCurrency: {
      name: "Kotti Ether",
      symbol: "KOT",
      decimals: 18,
    },
    infoURL: "https://explorer.jade.builders/?network=kotti",
    shortName: "kot",
    chainId: 6,
    networkId: 6,
  },
  {
    name: "ThaiChain",
    chain: "TCH",
    rpc: ["https://rpc.dome.cloud"],
    faucets: [],
    nativeCurrency: {
      name: "ThaiChain Ether",
      symbol: "TCH",
      decimals: 18,
    },
    infoURL: "https://thaichain.io",
    shortName: "tch",
    chainId: 7,
    networkId: 7,
  },
  {
    name: "Ubiq",
    chain: "UBQ",
    rpc: ["https://rpc.octano.dev", "https://pyrus2.ubiqscan.io"],
    faucets: [],
    nativeCurrency: {
      name: "Ubiq Ether",
      symbol: "UBQ",
      decimals: 18,
    },
    infoURL: "https://ubiqsmart.com",
    shortName: "ubq",
    chainId: 8,
    networkId: 8,
    slip44: 108,
    explorers: [
      {
        name: "ubiqscan",
        url: "https://ubiqscan.io",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "Optimism",
    chain: "ETH",
    rpc: ["https://mainnet.optimism.io/"],
    faucets: [],
    nativeCurrency: {
      name: "Ether",
      symbol: "ETH",
      decimals: 18,
    },
    infoURL: "https://optimism.io",
    shortName: "oeth",
    chainId: 10,
    networkId: 10,
    explorers: [
      {
        name: "etherscan",
        url: "https://optimistic.etherscan.io",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "Metadium Mainnet",
    chain: "META",
    rpc: ["https://api.metadium.com/prod"],
    faucets: [],
    nativeCurrency: {
      name: "Metadium Mainnet Ether",
      symbol: "META",
      decimals: 18,
    },
    infoURL: "https://metadium.com",
    shortName: "meta",
    chainId: 11,
    networkId: 11,
    slip44: 916,
  },
  {
    name: "Metadium Testnet",
    chain: "META",
    rpc: ["https://api.metadium.com/dev"],
    faucets: [],
    nativeCurrency: {
      name: "Metadium Testnet Ether",
      symbol: "KAL",
      decimals: 18,
    },
    infoURL: "https://metadium.com",
    shortName: "kal",
    chainId: 12,
    networkId: 12,
  },
  {
    name: "Diode Testnet Staging",
    chain: "DIODE",
    rpc: ["https://staging.diode.io:8443/", "wss://staging.diode.io:8443/ws"],
    faucets: [],
    nativeCurrency: {
      name: "Staging Diodes",
      symbol: "sDIODE",
      decimals: 18,
    },
    infoURL: "https://diode.io/staging",
    shortName: "dstg",
    chainId: 13,
    networkId: 13,
  },
  {
    name: "Flare Testnet Coston",
    chain: "FLR",
    rpc: ["https://coston-api.flare.network/ext/bc/C/rpc"],
    faucets: [
      "https://faucet.towolabs.com",
      "https://fauceth.komputing.org?chain=16&address=${ADDRESS}",
    ],
    nativeCurrency: {
      name: "Coston Flare",
      symbol: "CFLR",
      decimals: 18,
    },
    infoURL: "https://flare.xyz",
    shortName: "cflr",
    chainId: 16,
    networkId: 16,
    explorers: [
      {
        name: "blockscout",
        url: "https://coston-explorer.flare.network",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "Diode Prenet",
    chain: "DIODE",
    rpc: ["https://prenet.diode.io:8443/", "wss://prenet.diode.io:8443/ws"],
    faucets: [],
    nativeCurrency: {
      name: "Diodes",
      symbol: "DIODE",
      decimals: 18,
    },
    infoURL: "https://diode.io/prenet",
    shortName: "diode",
    chainId: 15,
    networkId: 15,
  },
  {
    name: "Flare Testnet Coston",
    chain: "FLR",
    rpc: ["https://coston-api.flare.network/ext/bc/C/rpc"],
    faucets: [
      "https://faucet.towolabs.com",
      "https://fauceth.komputing.org?chain=16&address=${ADDRESS}",
    ],
    nativeCurrency: {
      name: "Coston Flare",
      symbol: "CFLR",
      decimals: 18,
    },
    infoURL: "https://flare.xyz",
    shortName: "cflr",
    chainId: 16,
    networkId: 16,
    explorers: [
      {
        name: "blockscout",
        url: "https://coston-explorer.flare.network",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "ThunderCore Testnet",
    chain: "TST",
    rpc: ["https://testnet-rpc.thundercore.com"],
    faucets: ["https://faucet-testnet.thundercore.com"],
    nativeCurrency: {
      name: "ThunderCore Testnet Token",
      symbol: "TST",
      decimals: 18,
    },
    infoURL: "https://thundercore.com",
    shortName: "TST",
    chainId: 18,
    networkId: 18,
    explorers: [
      {
        name: "thundercore-blockscout-testnet",
        url: "https://explorer-testnet.thundercore.com",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "Songbird Canary-Network",
    chain: "SGB",
    icon: "songbird",
    rpc: [
      "https://songbird.towolabs.com/rpc",
      "https://songbird-api.flare.network/ext/C/rpc",
      "https://sgb.ftso.com.au/ext/bc/C/rpc",
      "https://sgb.lightft.so/rpc",
      "https://sgb-rpc.ftso.eu",
    ],
    faucets: [],
    nativeCurrency: {
      name: "Songbird",
      symbol: "SGB",
      decimals: 18,
    },
    infoURL: "https://flare.xyz",
    shortName: "sgb",
    chainId: 19,
    networkId: 19,
    explorers: [
      {
        name: "blockscout",
        url: "https://songbird-explorer.flare.network",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "Elastos Smart Chain",
    chain: "ETH",
    rpc: ["https://api.elastos.io/eth"],
    faucets: ["https://faucet.elastos.org/"],
    nativeCurrency: {
      name: "Elastos",
      symbol: "ELA",
      decimals: 18,
    },
    infoURL: "https://www.elastos.org/",
    shortName: "esc",
    chainId: 20,
    networkId: 20,
    explorers: [
      {
        name: "elastos esc explorer",
        url: "https://esc.elastos.io",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "Elastos Smart Chain Testnet",
    chain: "ETH",
    rpc: ["https://api-testnet.elastos.io/eth"],
    faucets: ["https://esc-faucet.elastos.io/"],
    nativeCurrency: {
      name: "Elastos",
      symbol: "tELA",
      decimals: 18,
    },
    infoURL: "https://www.elastos.org/",
    shortName: "esct",
    chainId: 21,
    networkId: 21,
    explorers: [
      {
        name: "elastos esc explorer",
        url: "https://esc-testnet.elastos.io",
        standard: "EIP3091",
      },
    ],
  },
  {
    name: "KardiaChain Mainnet",
    chain: "KAI",
    icon: "kardiachain",
    rpc: ["https://rpc.kardiachain.io"],
    faucets: [],
    nativeCurrency: {
      name: "KardiaChain",
      symbol: "KAI",
      decimals: 18,
    },
    infoURL: "https://kardiachain.io",
    shortName: "kardiachain",
    chainId: 24,
    networkId: 0,
    redFlags: ["reusedChainId"],
  },
];

export { networks, connectToNetworks };
